### ISSUE TITLE
DCM issue

### ISSUE THREAD

**Issue by delwende** [drcandacemakedamoore/cleanX#13]
Create a report to help us improve

**Describe the bug**
I had some issues with DCM images.

**Comment by drcandacemakedamoore** [comment]
Thank you so much for letting us know. As of right now the program only works with .jpeg images which can be extracted from dcm/DCM/DICOM files, and you can use libraries like pydicom to extract them. We are considering adding functionality to automatically convert images from DICOM and maybe also create png versions of the files as this is a lossless file format. Did you already extract jpg files, and still have issues?

**Comment by wvxvw** [comment]
Just a short heads-up: I'm now investigating the possibility to use cleanX with `pydicom`. `pydicom` has conditional dependency on few libraries, of which `gdcm` seems like a very important one. The problem here is that DICOM archives can contain multitude of image formats in them, some of them are less common than others, however, it looks like GDCM project covers a substantial fraction of all the possible embedded image formats. On the other hand, the project seems to be difficult to integrate with other Python packages.

Conda-forge channel has several labels for this package. Not sure why, but it's worth trying to install it from several labels and see if any of them would work with the Python version we are aiming for. Unfortunately, at this time it seems to be very difficult to support multiple Python versions due to the constraints on dependencies. Anyways, @drcandacemakedamoore could you try these:

```
conda install -c conda-forge/label/cf201901 gdcm
conda install -c conda-forge/label/cf202003 gdcm
```

And see if either one will work with the Python and `conda` environment you have? I'll try to do this on Linux at the same time.

**Comment by wvxvw** [comment]
NB.

```
conda install -c conda-forge/label/cf202003 gdcm
```

Worked on Linux with Python 3.7

**Comment by drcandacemakedamoore** [comment]
I actually already tried the versions you suggested Oleg, and they didn't work with Python 3.7 in a Microsoft Windows environment. I think we may need to make a new conda distribution of gdcm, but please let me check with some engineers in this area who work with DICOMs to see if one already exists.

**Comment by drcandacemakedamoore** [comment]
We added a function that allows you to extract/copy out the jpg from DICOM files if you have the simpleITK library installed (rip_out_jpgs_sitk). One made for for the case that you have pydicom is coming.

**Comment by drcandacemakedamoore** [comment]
We also added a function to extract/copy out the jpg from DICOM files if you have the pydicom library. Please let us know if you are interested in any other common dicom-related library for a library-based extraction code.

**Comment by drcandacemakedamoore** [comment]
As the library currently works if you have either pydicom or simpleITK library, you can turn your DICOMs into JPEGS. We have not heard that you can not get either, so we are considering the issue closed.
