### ISSUE TITLE
Joss issues

### ISSUE THREAD

**Issue by henrykironde** [drcandacemakedamoore/cleanX#35]
This is a list of some improvements/suggestions or issues that may need clarifications. 

- [x] Is this file needed GNU GENERAL PUBLIC LICENSE.txt?
- [x] Include Conda badges https://anaconda.org/doctormakeda/cleanx/badges
- [x] Make sure that the test badges link to the test builds. Currently, they link to the image of the badge. [![Sanity](https://github.com/drcandacemakedamoore/cleanX/actions/workflows/on-commit.yml/badge.svg)](https://github.com/drcandacemakedamoore/cleanX/actions/workflows/on-commit.yml)
- [x] Create a `paper` folder for the paper files and include a copy of the LICENSE file.
- [x] Include some examples on how to get started in the readme file. The same applies to the documentation. I would expect at least some sort of getting started guide.

- [x] Since version v0.1.9 was released, I would expect the current changes to have v0.2.0.dev as the version for these changes in development. Later to be released as v0.2.0. But if you desire to have the current pattern, thats fine.
- [x] Move all document files to a docs folder. I think `readthedocs` could also enable the docs have two versions, the stable and the latest.
- [x] In the `Jupyter` we have paths like `'D:/projects/cleanX'` It would be nice to start by getting the current project's directory and then use relative paths with join. 
For example: 
```python
dicomfile_directory1 = 'D:/projects/cleanX/test/dicom_example_folder'
example = pd.read_csv("D:/projects/cleanX/workflow_demo/martians_2051.csv")
# To
working_dir = "Path to project home"
example_path = os.path.normpath(os.path.join(working_dir, "workflow_demo/martians_2051.csv"))
example = pd.read_csv(example_path)
```
It would be nice to normalize the paths. This will help Windows users who have a hard time with / and \ characters

**Comment by wvxvw** [comment]
I'll see what I can do about the rest. Quick comment on documentation first: there probably won't be readthedocs integration in the near future due to how they require us to submit our code. There are multiple problems there, to name a few: we need to install shared libraries necessary for Tesseract to work, but that's not possible, because we have no control over the environment in which the documentation is built.

There is some way to mock dependencies that won't be installed, unfortunately, that would require modifying the `install_requires` part of `setup.py` in a way that doesn't list the actually required packages... bottom line: we tried, and readthedocs is just too hard to integrate with / not worth the effort. I just need to remove the shreds of this failed attempt.

Also, I'm not quite sure about what do you mean when you write about moving documentation to docs folder. API documentation is all generated... there isn't any special folder for it as it's published as GitHub pages, separately from the rest of the project. Technically, when it's generated, it will end up under `./build/sphinx/html/...` but I don't think this is relevant to anyone.

**Comment by henrykironde** [comment]
I totally understand the readmedocs problem in case where we are including shared libraries. For the part that of the docs folder, It would be nice to have all the doc resources in the docs folder. i.e  `Makefile`, `make.bat`, `source`

**Comment by wvxvw** [comment]
I also looked into publishing multiple versions of documentation... And yes, there's something we could do, but some other things require a lot of work. The problem here is that two Sphinx "extensions" that aspire to do this are, basically, broken. The first one was unmaintained since Python 3.5 and doesn't work with any older versions, the second one doesn't integrate with `setuptools`, which is how we build the documentation. Not only that, it still requires a lot of manual labor to add versions (so, basically, if you go down that path, it's probably easier to just do it yourself by editing Sphinx HTML templates).

**Comment by wvxvw** [comment]
> all the doc resources in the docs folder. i.e Makefile, make.bat, source

Oh, yeah... those. Well, Makefile and make.bat are irrelevant. I simply forgot to delete them. I can rename source to docs though.

**Comment by wvxvw** [comment]
@henrykironde 

> Make sure that the test badges link to the test builds. Currently, they link to the image of the badge.

I just checked with documentation: https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge this is how it is supposed to work. I.e. the URL for the badge is the way the documentation tells us to do, specifically:

> You reference the workflow by the name of your workflow file.
>
> 
> ``` markdown
> ![example workflow](https://github.com/<OWNER>/<REPOSITORY>/actions/workflows/<WORKFLOW_FILE>/badge.svg)
> ```

I don't believe there's any way to point to the latest GitHub Actions run, even the concrete URL is only available *after* the job starts, so I cannot add it to the README in the same commit that starts the CI job.

**Comment by henrykironde** [comment]
<img width="1553" alt="Screen Shot 2021-08-21 at 12 21 01 PM" src="https://user-images.githubusercontent.com/5192965/130328360-55148d92-16a8-49f1-a212-12c1dddf8fdd.png">
If you open your workflows you will be able to create the status badge the right way. 
This will enable contributors and users to easily check out the builds.

<img width="1282" alt="Screen Shot 2021-08-21 at 12 23 08 PM" src="https://user-images.githubusercontent.com/5192965/130328412-aa1fc39c-b721-41bd-8c9b-15c71262a742.png">

**Comment by wvxvw** [comment]
@henrykironde Yes, I tried it. It just links to the Actions tab of the project... it's not really useful either. Why does it make a difference? That won't help anyone to find their builds, unfortunately...

**Comment by wvxvw** [comment]
> Since version v0.1.9 was released, I would expect the current changes to have v0.2.0.dev as the version for these changes in development. Later to be released as v0.2.0. But if you desire to have the current pattern, thats fine.

All the changes are cosmetic so far. They don't touch the code. I.e. there's no API changes. We use semantic versioning with the semantics:

1. Most significant component means backwards-incompatible changes to API.
2. Second most significant component means backwards-compatible changes to API.
3. Least significant component means no changes to API.

We don't believe in using anything other than digits in versions. This creates a lot of problems for dependency constraint solvers s.a. those in `pip` or `conda`. So we aren't going to have versions for `dev`, `alpha`, `rc` etc. That's intended.

**Comment by henrykironde** [comment]
> Yes, I tried it. It just links to the Actions tab of the project... it's not really useful either. Why does it make a difference? That won't help anyone to find their builds, unfortunately...
 
The goal is to make sure the submission is as good as the dependencies that are in the project. Take an example of https://github.com/matplotlib/matplotlib. They provide the links to the builds in the right markdown way.
When it comes to dependencies, developers will usually check on the builds of the packages they are utilizing. In this way you can have a better idea when the build failed and why and how that failure transitions to your package.

**Comment by henrykironde** [comment]
> All the changes are cosmetic so far. They don't touch the code. I.e. there's no API changes. We use semantic versioning with the semantics:

There could be a slight disagreement on the way you version the package. In case you want to use this style of versioning, I recommend creating a new branch. Call this branch development or any name. Once a release is made, no commits should be made to the main. 
All commits should be to the dev branch, and when it is time to release you merge the dev to master.
**Why this is a recommended case:**
My software downloads scientific packages and analyses/detect the changes in code by version. I always build from the source because I don't like already build binaries or installers. As I detect for changes and malware, your package has a release version and a hash value, after you change the code, the hash of the code changes but the version is still the same. Right there other people using your source may have problems.

**Comment by henrykironde** [comment]
For the paper folder the license should not have the postfix `_copy`.

**Comment by wvxvw** [comment]
> Why this is a recommended case:
> My software downloads scientific packages and analyses/detect the changes in code by version. I always build from the source because I don't like already build binaries or installers. As I detect for changes and malware, your package has a release version and a hash value, after you change the code, the hash of the code changes but the version is still the same. Right there other people using your source may have problems.

People building from source chose their own fate. If they don't want to rely on the distributable package built by the package maintainers, it's their own choice. Which I can understand, but can accommodate on the basis of available free time and ease of use for other people involved with the project.

This package is mostly written by medical professional, who aspire to be software developers on the side. I'm not a medical professional, and, normally, I follow the practices you recommend. However, what you recommend is uncomfortable and confusing to people who aren't professional software developers.

There's another aspect to it: the CI-related code necessary to release versions may have bugs. It's unfortunate, but this is how these free services work. I cannot test CI code in advance and make sure that it will work on the first try. This means that releases will sometimes fail. There is no way to roll out a release other than from the main branch. So, the changes will have to be made to the main branch even if nothing in the released code changes.

Yet another aspect of it is the documentation. In order to see that documentation is generated properly one has to do it from the main branch. While it's possible to see most of the changes from side branches, ultimately, the proof that it works is by generating it from the main branch. So, anyone who works on documentation is bound to make changes to the main branch. Again, this is an unfortunate aspect of how GitHub Actions work, and how the free hosting of documentation works.

So, in an ideal world, where I'm self-hosting my repository and organise CI and documentation publishing in whatever way I want, I could have main branch dedicated to releases only. This is not possible if using GitHub though outside of trivial cases.

**Comment by wvxvw** [comment]
> The goal is to make sure the submission is as good as the dependencies that are in the project. Take an example of https://github.com/matplotlib/matplotlib. They provide the links to the builds in the right markdown way.

1. Our links are in exactly the same format as theirs.
2. They are equally useless... I mean, they just point to the Actions tab.

**Comment by henrykironde** [comment]
Well I will disagree with some of your opinions, If I have sometime I could help. Documentation should be tested locally first. Then push to whichever branch, that is why we have stable docs and latest docs.

> However, what you recommend is uncomfortable and confusing to people who aren't professional software developers.

That is why we are here to help as much as possible so that you publish a state of art project.

>  I cannot test CI code in advance and make sure that it will work on the first try. 

We can change the workflow.
 1. Do not commit directly to the main. This is a very good practice. make branches and create pull requests. The CI should pass to allow you to merge the changes to master. In that way we are sure to a good percentage that we shall have bug free code.
2. 
> There is no way to roll out a release other than from the main branch.

Releases are always from the main branch. Basing on the way you version your software, if you only commit to a dev branch, at the time of release you merge the dev to main and create a release.

3. >  the proof that it works is by generating it from the main branch
We can have tests for the dev branch too.

Let me know when you get time, I could probably spare an hour to help out with some of the enhancement so that we can be on the same page.

**Comment by wvxvw** [comment]
> Documentation should be tested locally first. Then push to whichever branch, that is why we have stable docs and latest docs.

In an ideal world: yes. On GitHub: no. Here's the reason: the version of the library is determined by the latest tag on the current branch. If you generate documentation from a branch other than main, you need to make sure the latest tag on that branch is the same as the one on main. This may not always be possible.

A significant portion of work needed to publish documentation is done in GitHub actions. They are impossible to test locally. Because it's a hosted proprietary service. You can imitate some of it, but you cannot run it exactly as it does on GitHub. Even to develop an imitation of these GitHub actions will be a huge waste of time, that is completely unjustified if compared to simplicity of just running them on GitHub and watching the results.

Just to illustrate my point better: the images built for CI in GitHub are some rather weird mix-and-mash of Linux distros. This, for example, creates unexpected problems when our code tries to work around Tesseract's bugs related to Unicode locale support: who could've imagine that `ldconfig` wouldn't be installed on Linux? And yet, it isn't. I don't have direct access to GitHub CI images, not to mention that they keep changing every few weeks, and I have no control over what's going to be inside those images next month or, perhaps, next week. If I don't test in actual GitHub Actions environment, I will not discover the problems.

Trust me, I'm used to running CI with dozens of thousands of jobs a day, supporting projects much bigger and more complex than this one. What I do is based on many years of experience of doing this. I can recognize the zeal of wanting to do things "the right way". But, the truth of it is that CI needs to serve the people who work on the project, and make *their* life more convenient. If "the right way" is inconvenient, it is the wrong way. No matter how much you want to believe the opposite.

> Do not commit directly to the main. This is a very good practice. 

You can change workflow in your projects however you like... I already explained why workflow in this project is the way it is and will remain the way it is. Thank you for your suggestion, but I'm not interested in changing it.

**Comment by wvxvw** [comment]
>  Include some examples on how to get started in the readme file. The same applies to the documentation. I would expect at least some sort of getting started guide.

There are now examples in the README: https://github.com/drcandacemakedamoore/cleanX/blame/main/README.md#L135

**Comment by drcandacemakedamoore** [comment]
I went through the notebooks and made all the paths relative. I hope this is easier for users to understand.

**Comment by drcandacemakedamoore** [comment]
Hi, @henrykironde we have not heard from you or anyone else at JOSS in a while. We have kept the main branch unchanged (except a few lines to deal with some security issues ) but now feel we made some substantial process on the develop branch. Do you think the review should take much longer? We can freeze the develop branch as well if this helps.

**Comment by henrykironde** [comment]
Thanks for the update @drcandacemakedamoore I think we were waiting for a confirmation from you, that everything is ready to review again. Reviews usually take a short time (2-3 weeks). In Cleanx's case, we could not install the software to test it. Since you have reminded us, I will go ahead and test it. 

> We have kept the main branch unchanged....but now feel we made some substantial process on the develop branch.

Authors should update their branches based on the Joss requests(issues), hence no need to freeze the branch

**Comment by henrykironde** [comment]
Thank you for taking time to resolve these issues
